# pandas DataFrame 열 지우기 및 나누기

기계 학습 모델 학습을 준비 할 때 특정 열을 삭제하거나 DataFrame의 특정 열을 새 DataFrame으로 분할해야하는 경우가 많습니다.

우리는 pandas 라이브러리와 탐색할 DataFrame이 필요합니다.

In [1]:
import pandas as pd


더 많은 열이있는 더 큰 csv 파일을 로드합니다. ** flight_delays.csv **는 항공편과 항공편 지연에 대한 정보를 제공합니다.

In [2]:
delays_df = pd.read_csv('Data/flight_delays.csv')
delays_df.head()

,FL_DATE,OP_UNIQUE_CARRIER,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE
0,2018-10-01,WN,N221WN,802,ABQ,BWI,905,903,-2,1450,1433,-17,225,210,197,1670
1,2018-10-01,WN,N8329B,3744,ABQ,BWI,1500,1458,-2,2045,2020,-25,225,202,191,1670
2,2018-10-01,WN,N920WN,1019,ABQ,DAL,1800,1802,2,2045,2032,-13,105,90,80,580
3,2018-10-01,WN,N480WN,1499,ABQ,DAL,950,947,-3,1235,1223,-12,105,96,81,580
4,2018-10-01,WN,N227WN,3635,ABQ,DAL,1150,1151,1,1430,1423,-7,100,92,80,580

## DataFrame에서 열 지우기

기계 학습을 위해 데이터를 준비 할 때 모델을 학습하기 전에 DataFrame에서 특정 열을 삭제해야 할 수 있습니다.

예시:
비행 지연 시간 (ARR_DELAY)을 예측하기 위해 모델을 학습한다고 가정 해보십시오.

모델이 예정된 도착 시간 (CRS_ARR_TIME)과 실제 도착 시간 (ARR_TIME)을 알고있는 경우 모델은 ARR_DELAY = ARR_TIME-CRS_ARR_TIME을 신속하게 파악합니다.

향후 항공편의 도착 시간을 예측할 때 도착 시간 (ARR_TIME) 값이 없습니다. 따라서 ARR_DELAY를 예측하도록 모델을 훈련 할 때 추가로 사용되지 않도록 DataFrame에서 이 열을 제거해야합니다.

In [3]:
# Remove the column ARR_TIME from the DataFrane delays_df

#delays_df = delays_df.drop(['ARR_TIME'],axis=1)
new_df = delays_df.drop(columns=['ARR_TIME'])
new_df.head()

,FL_DATE,OP_UNIQUE_CARRIER,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,CRS_ARR_TIME,ARR_DELAY,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE
0,2018-10-01,WN,N221WN,802,ABQ,BWI,905,903,-2,1450,-17,225,210,197,1670
1,2018-10-01,WN,N8329B,3744,ABQ,BWI,1500,1458,-2,2045,-25,225,202,191,1670
2,2018-10-01,WN,N920WN,1019,ABQ,DAL,1800,1802,2,2045,-13,105,90,80,580
3,2018-10-01,WN,N480WN,1499,ABQ,DAL,950,947,-3,1235,-12,105,96,81,580
4,2018-10-01,WN,N227WN,3635,ABQ,DAL,1150,1151,1,1430,-7,100,92,80,580

** inplace ** 매개 변수를 사용하여 원래 DataFrame에서 열을 삭제하도록 지정합니다

In [4]:
# Remove the column ARR_TIME from the DataFrame delays_df

#delays_df = delays_df.drop(['ARR_TIME'],axis=1)
delays_df.drop(columns=['ARR_TIME'], inplace=True)
delays_df.head()

,FL_DATE,OP_UNIQUE_CARRIER,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,CRS_ARR_TIME,ARR_DELAY,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE
0,2018-10-01,WN,N221WN,802,ABQ,BWI,905,903,-2,1450,-17,225,210,197,1670
1,2018-10-01,WN,N8329B,3744,ABQ,BWI,1500,1458,-2,2045,-25,225,202,191,1670
2,2018-10-01,WN,N920WN,1019,ABQ,DAL,1800,1802,2,2045,-13,105,90,80,580
3,2018-10-01,WN,N480WN,1499,ABQ,DAL,950,947,-3,1235,-12,105,96,81,580
4,2018-10-01,WN,N227WN,3635,ABQ,DAL,1150,1151,1,1430,-7,100,92,80,580

우리는 보통 숫자 값(예 : 거리, 분, 무게)나 숫자가 아닌 정량적인 값(예 : 항공편이 출발한 공항, 항공편을 운항한 항공사)을 기반으로 예측하기 위해 다양한 기술을 사용합니다.

정량적 데이터는 모델을 학습하기 전에 별도의 DataFrame으로 이동할 수 있습니다.

그리고 예측을 수행하는데 도움이 될 수 있다고 생각되는 값(특징)과는 별도의 DataFrame에 ARR_DELAY 레이블이라는 예측하려는 값을 넣어야합니다.

기존 데이터 프레임의 열에서 새 데이터 프레임을 생성할 수 있어야합니다.

In [ ]:
# desc_df의 이름을 가지는 DataFrame을 생성하세요
# 모든 행을 포함하세요.
# ORIGIN, DEST, OP_CARRIER_FL_NUM, OP_UNIQUE_CARRIER, TAL_NUM 열을 포함하세요.

desc_df = delays_df.loc[:,['ORIGIN', 'DEST', 'OP_CARRIER_FL_NUM', 'OP_UNIQUE_CARRIER', 'TAIL_NUM']]
desc_df.head()